name: Publish ele to PyPI and TestPyPI

on:
  push:
    branches:
      - master
  release:
    types:
      - published


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Build dist
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish ele to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish ele to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
        if: github.event_name == 'release'
